[package]
name = "anchor-spl"
version = "0.29.0"
authors = ["Anchor Maintainers <accounts@200ms.io>"]
edition = "2021"
license = "Apache-2.0"
description = "Anchor CPI for Solana Program Library (SPL)"
repository = "https://github.com/coral-xyz/anchor"

[features]
default = []
dex = []
gated-token = []
idl-build = [
    "anchor-lang/idl-build",
    "spl-associated-token-account/idl-build",
    "spl-token/idl-build",
]
memo = ["spl-memo"]

[dependencies]
anchor-lang = { git = "https://github.com/hamkj7hpo/anchor.git", rev = "dbfdadca848af65a4bd8b48b777a30ca9af1430d", features = ["init-if-needed"] }
solana-program = { git = "https://github.com/hamkj7hpo/solana.git", rev = "5208a7870826307290c30b7d80768f40267433a1" }
spl-associated-token-account = { git = "https://github.com/hamkj7hpo/associated-token-account.git", rev = "a504320c1f48537eb8391c3e5621d9c971660fca" }
spl-token = "4.0.0"
spl-memo = { version = "4.0.0", optional = true }
