[package]
name = "anchor-spl"
version = "0.30.1"
description = "Anchor SPL - Solana Program Library programs for Anchor"
authors = ["Anchor Maintainers"]
repository = "https://github.com/hamkj7hpo/anchor"
license = "Apache-2.0"
edition = "2021"

[features]
default = []
cpi = ["anchor-lang/cpi"]

[dependencies]
anchor-lang = { git = "https://github.com/hamkj7hpo/anchor.git", branch = "safe-pump-compat" }
solana-program = { git = "https://github.com/hamkj7hpo/solana.git", branch = "safe-pump-compat" }
spl-token = { git = "https://github.com/hamkj7hpo/solana-program-library.git", branch = "safe-pump-compat", package = "spl-token", features = ["no-entrypoint"] }
spl-associated-token-account = { git = "https://github.com/hamkj7hpo/associated-token-account.git", branch = "safe-pump-compat", default-features = false }
spl-token-2022 = { git = "https://github.com/hamkj7hpo/token-2022.git", branch = "safe-pump-compat", package = "spl-token-2022", default-features = false }

[lib]
crate-type = ["cdylib", "lib"]
name = "anchor_spl"
